global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel:8889']
#  - job_name: 'traefik'
#    static_configs:
#      - targets: ['traefik:9100']